# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
default_stages: [commit]
default_language_version:
  python: python3

repos:
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.3.2.9003
    hooks:
      - id: style-files
        additional_dependencies:
          - r-lib/styler
        args:
          ['--ignore-start="^# styler: off$"', '--ignore-stop="^# styler: on$"']
        exclude: >
          (?x)^(
          man/.*|
          tests/testthat/_snaps/.*\.md|
          )$
      - id: no-browser-statement
      - id: no-debug-statement
      - id: parsable-R
      - id: deps-in-desc
      - id: spell-check
        additional_dependencies:
          - pdftools
        exclude: >
          (?x)^(
          \.github/.*\.yaml|
          data/.*|
          tests/testthat/.*|
          touchstone/config\.json|
          (.*/|)\.Rprofile|
          (.*/|)\.Renviron|
          (.*/|)\.gitignore|
          (.*/|)NAMESPACE|
          (.*/|)WORDLIST|
          (.*/|)\.travis.yml|
          (.*/|)appveyor.yml|
          (.*/|)\.Rbuildignore|
          (.*/|)\.pre-commit-.*|
          .*\.[rR]|
          .*\.Rproj|
          .*\.py|
          .*\.feather|
          .*\.rds|
          .*\.Rds|
          .*\.sh|
          .*\.RData|
          )$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-case-conflict
      - id: check-yaml
      - id: mixed-line-ending
      - id: file-contents-sorter
        files: "\\.Rbuildignore$"
      - id: end-of-file-fixer
        exclude: >
          (?x)^(
          man/.*|
          tests/testthat/_snaps/.*\.md|
          )$

  - repo: https://github.com/lorenzwalthert/gitignore-tidy
    rev: "475bf5d96927a1887ce2863ff3075b1d7240bc51"
    hooks:
      - id: tidy-gitignore

ci:
  autoupdate_schedule: monthly
