# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
default_stages: [commit]
default_language_version:
  python: python3

repos:

  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.3.2.9003
    hooks:
      - id: style-files
        additional_dependencies:
          - r-lib/styler
        args:
          ['--ignore-start="^# styler: off$"', '--ignore-stop="^# styler: on$"']
      - id: use-tidy-description
      - id: parsable-R
      - id: no-browser-statement

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: file-contents-sorter
        files: "\\.Rbuildignore$"
      - id: end-of-file-fixer

  - repo: https://github.com/lorenzwalthert/gitignore-tidy
    rev: 475bf5d96927a1887ce2863ff3075b1d7240bc51
    hooks:
      - id: tidy-gitignore

default_stages: ["commit"]

ci:
  autoupdate_schedule: monthly
