# All available hooks: https://pre-commit.com/hooks.html
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.0.0.9026
    hooks:
    # -   id: lintr
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: readme-rmd-rendered
    #  R package development
    -   id: roxygenize
    -   id: use-tidy-description
    -   id: deps-in-desc
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=200']
-   repo: https://github.com/lorenzwalthert/precommit-markdown-link-check
    rev: v0.0.0.9002  # Use the sha / tag you want to point at
    hooks:
    -   id: markdown-link-check
