# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.3.2.9001
    hooks:

    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style, --cache-root=styler-perm]
        exclude: >
          (?x)^(
          tests/testthat/in/.*|
          renv/.*
          )$

    -   id: use-tidy-description
    -   id: spell-check
        exclude: >
          (?x)^(
          \.github/.*\.yaml|
          data/.*|
          tests/testthat/.*|
          touchstone/config\.json|
          (.*/|)\.Rprofile|
          (.*/|)\.Renviron|
          (.*/|)\.gitignore|
          (.*/|)NAMESPACE|
          (.*/|)WORDLIST|
          (.*/|)\.travis.yml|
          (.*/|)appveyor.yml|
          (.*/|)\.Rbuildignore|
          (.*/|)\.pre-commit-.*|
          .*\.[rR]|
          .*\.Rproj|
          .*\.py|
          .*\.feather|
          .*\.rds|
          .*\.Rds|
          .*\.sh|
          .*\.RData|
          .*-in_tree
          )$

    -   id: parsable-R
        exclude: >
          (?x)^(
          tests/testthat/in/.*|
          )$

    -   id: no-browser-statement
        exclude: >
          (?x)^(
          tests/testthat/in/.*|
          )$

    -   id: no-debug-statement
        exclude: >
          (?x)^(
          tests/testthat/in/.*|
          )$

    -   id: deps-in-desc
        exclude: >
          (?x)^(
          tests/testthat/in/.*|
          inst/renv-update\.R|
          renv/activate.R|
          vignettes/FAQ\.Rmd|
          )$

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: end-of-file-fixer
        exclude: '\.Rd' # sometimes roxygen fails to generate EOF blank line.
    -   id: file-contents-sorter
        files: '^\.Rbuildignore$'

-   repo: https://github.com/pre-commit-ci/pre-commit-ci-config
    rev: v1.5.1
    hooks:
    # Only reuiqred when https://pre-commit.ci is used for config validation
    -   id: check-pre-commit-ci-config

-   repo: https://github.com/lorenzwalthert/gitignore-tidy
    rev: a2260df7cc08de00d7312aeff68cea6bcba48c42
    hooks:
    -   id: tidy-gitignore

-   repo: local
    hooks:
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .Rdata, .csv and similar.
        language: fail
        files: '\.(Rhistory|csv|RData|Rds|rds)$'
        # `exclude: <regex>` to allow committing specific files.

default_stages: ["commit"]

ci:
    skip: [consistent-release-tag, spell-check-ordered-exclude]
    autoupdate_schedule: monthly
