language: r
r:
  - release
  - devel
latex: true
warnings_are_errors: TRUE

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libproj-dev
      - libmpfr-dev

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=true
    - _R_CHECK_CRAN_INCOMING_=true

cache:
  - packages
  - ccache

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

r_packages:
  - Rcpp
  - RcppEigen
  - mvtnorm
  - rstan
  - StanHeaders
  - LaplacesDemon
  - logspline
  - testthat
  - devtools
  - remotes
  - knitr
  - rmarkdown
  - coda
  - rstantools
  - bridgesampling
  - BH
  - metaBMA

r_github_packages:
  - jimhester/lintr
  - r-lib/covr

before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fext-numeric-literals -fPIC" >> ~/.R/Makevars

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'covr::coveralls()'
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
