language: r
r: devel

warnings_are_errors: TRUE
r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

cache:
  - packages
  - ccache

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libproj-dev

before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'covr::coveralls()'
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
