# documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: trusty
latex: true
warnings_are_errors: true
cache:
  - packages
  - ccache

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

env:
  global:
    - R_MAX_NUM_DLLS=999
    - _R_CHECK_FORCE_SUGGESTS_=true
    - _R_CHECK_CRAN_INCOMING_=true

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libproj-dev

#r_check_args: "--run-dontrun"

notifications:
  email:
  on_success: change
  on_failure: change

jobs:
  include:
    - os: linux
      r: release
      r_github_packages:
        - jimhester/lintr
        - r-lib/covr
    - os: linux
      r: devel
      r_github_packages:
        - jimhester/lintr
        - r-lib/covr


before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars


after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'covr::coveralls()'
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
