# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <tidy_model_parameters>
  # <tidy_model_effectsize>
  ".",
  # <contingency_table>
  ".counts",
  # <contingency_table>
  # <oneway_anova>
  # <pairwise_comparisons>
  ".f",
  # <meta_analysis>
  ".f.args",
  # <contingency_table>
  ".f.es",
  # <meta_analysis>
  # <pairwise_comparisons>
  ".fn",
  # <meta_analysis>
  # <pairwise_comparisons>
  ".ns",
  # <long_to_wide_converter>
  # <oneway_anova>
  # <pairwise_comparisons>
  ".rowid",
  # <add_expression_col>
  "df",
  # <oneway_anova>
  "digits.df",
  # <oneway_anova>
  "digits.df.error",
  # <centrality_description>
  "estimate",
  # <pairwise_comparisons>
  "group1",
  # <pairwise_comparisons>
  "group2",
  # <add_expression_col>
  "method",
  # <add_expression_col>
  # <centrality_description>
  "n.obs",
  # <long_to_wide_converter>
  "nested_data",
  # <pairwise_comparisons>
  "p.value",
  # <tidy_model_parameters>
  "r.squared",
  # <pairwise_comparisons>
  # <tidy_model_expressions>
  "term",
  NULL
))
