# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "method", # <add_expression_col>
  "n.obs", # <add_expression_col>
  "df", # <add_expression_col>
  "n.obs", # <centrality_description>
  "estimate", # <centrality_description>
  ".counts", # <contingency_table>
  ".f", # <contingency_table>
  ".f.es", # <contingency_table>
  ".", # <tidy_model_parameters>
  "r.squared", # <tidy_model_parameters>
  ".", # <tidy_model_effectsize>
  ".rowid", # <long_to_wide_converter>
  "nested_data", # <long_to_wide_converter>
  ".ns", # <meta_analysis>
  ".fn", # <meta_analysis>
  ".f.args", # <meta_analysis>
  ".rowid", # <oneway_anova>
  "k.df", # <oneway_anova>
  "k.df.error", # <oneway_anova>
  ".f", # <oneway_anova>
  ".rowid", # <pairwise_comparisons>
  ".f", # <pairwise_comparisons>
  "group1", # <pairwise_comparisons>
  "group2", # <pairwise_comparisons>
  ".ns", # <pairwise_comparisons>
  ".fn", # <pairwise_comparisons>
  "term", # <pairwise_comparisons>
  "p.value", # <pairwise_comparisons>
  "term", # <tidy_model_expressions>
  NULL
))
