# Run tests in random order
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: check-random-test-order

jobs:
  check-random-test-order:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "devel"
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          extra-packages: |
            local::.

      - name: Run Tests in Random Order
        run: |
          options(crayon.enabled = TRUE)
          withr::local_envvar(TESTTHAT_PARALLEL = "FALSE")
          testthat::test_dir("tests", shuffle = TRUE)
        shell: Rscript {0}
