# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Trigger once a week at 00:00 on Sunday
    - cron: "0 0 * * SUN"

name: lint

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          extra-packages: |
            r-lib/lintr
            local::.
          needs: lint

      - name: Lint
        run: |
          library(lintr)
          lint_package(linters = linters_with_defaults(
            absolute_path_linter = NULL,
            commented_code_linter = NULL,
            cyclocomp_linter(20L),
            extraction_operator_linter = NULL,
            implicit_integer_linter = NULL,
            line_length_linter(120L),
            object_name_linter = NULL,
            object_length_linter(50L),
            object_usage_linter = NULL,
            nonportable_path_linter = NULL,
            string_boundary_linter = NULL,
            strings_as_factors_linter = NULL,
            todo_comment_linter = NULL,
            undesirable_function_linter = NULL,
            unused_import_linter = NULL,
            defaults = linters_with_tags(tags = NULL)
          ))
        shell: Rscript {0}
        # env:
        #   LINTR_ERROR_ON_LINT: true
